package org.example.qaTransactionTeam.backEnd.admin;

import io.restassured.http.ContentType;
import org.apache.log4j.Logger;
import org.example.qaTransactionTeam.backEnd.token.Trans_token_payhub;
import org.example.qaTransactionTeam.backEnd.utils.Restful;

import static io.restassured.RestAssured.given;

public class Trans extends Restful {

    private static final Logger logger = Logger.getLogger(Trans.class);
    private final Trans_token_payhub token = new Trans_token_payhub();

    public void getDetails(String params){
        logger.info("getDetails");
        request(given()
                .contentType(ContentType.JSON).log().all()
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMU1dxSEYzWUF0UDkzMmNXdm5ESXBzOHhqaHRQeWxiN0JOV2prVWhqcVhrIn0.eyJleHAiOjE3ODA0NzQyNTQsImlhdCI6MTc4MDQ3MzM1NCwianRpIjoib25ydHJvOjFhZGY4OTdlLTk2YmYtMzcxNC1iMTA3LWRhY2I5ZDdlYzFkYyIsImlzcyI6Imh0dHBzOi8vYXV0aC50ZXN0LWZ1aWIuY29tL2F1dGgvcmVhbG1zL3B1bWIiLCJhdWQiOlsicGF5aHViX2FkbWluIiwiUEhUUk4iLCJQSEFETVAiLCJPREIiLCJhY2NvdW50Il0sInN1YiI6IjY3ZjZjMjQ2LWI4Y2YtNGU0NS05OGQ1LWM0ZTE1NGZlMzA1NyIsInR5cCI6IkJlYXJlciIsImF6cCI6InBheWh1Yl9hZG1pbiIsInNpZCI6IkthZk9BaEZOUEJhRUxCMU9MbEI1SVA5MSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vMTI3LjAuMC4xOjgwODAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXB1bWIiXX0sInJlc291cmNlX2FjY2VzcyI6eyJQSFRSTiI6eyJyb2xlcyI6WyJwaF90ZyJdfSwiUEhBRE1QIjp7InJvbGVzIjpbInRybl92aWV3IiwicGhwcl9wcmMiLCJjYWJfZWRpZ19zZiIsInBoYWNxIiwicGhhY3FfbWdyIiwiY2FiX29jaF9zdSIsInBocHIiLCJwYmxfb3AiLCJwYmxfbW5nIiwicGJsX3A0cCIsInBibF9hY3EiLCJwYmxfc3VwIiwidHJuX3JwcnQiXX0sIk9EQiI6eyJyb2xlcyI6WyJhY2NfciJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19LCJwYXlodWJfYWRtaW4iOnsicm9sZXMiOlsicGhhZG1fY3Rybl9pbmYiLCJjaGtfb3AiLCJwaGFkbV9jdHJuIiwicGhfb3B3cyIsInBoYWRtX2dycF9wbnRzIiwidm9jIiwicGhhZG1fY3Rybl9tZXJjaCIsImNuY2xfb3AiLCJwaGFkbV9zcnZfbmMiLCJwaGFkbV9zcnZfdmlldyIsInBoYWRtX21lcmNoX2VkaXQiLCJwaF9leHRfY2RiIiwicGhhZG1fZ3JwX2NtbSIsInZvY19tbmciLCJwaGFkbV9jdHJuX2VkIiwicGhhZG1fZ3JwX3NydiIsInBoX2lwc19vcHIiLCJwaF9pcHNfYWRtIiwicGhhZG1fc3J2X3BiIiwiZXB0X3Byb2MiLCJlcHRfb3BzIiwicGhfc2Jfb3AiLCJlcnIiLCJyZWdfb3AiLCJlcHQiLCJwaGFkbV9tZXJjaCIsInBoX29wdyIsInBoX2hoX29wIiwicGhfb3ByIiwia3Z0X3NuZCIsInBoYWRtX3Nydl9tbmciLCJwaGFkbV9tZXJjaF92aWV3IiwicGhhZG1fc3J2X2VkaXQiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InN2Y19waF90ZXN0X3RybiJ9.L_4CVQioBQSXHZnvvkx1_J3DqwJ48P4dyMp5DggGVxxH4hX2e4KP8ORe81IcKS8vR9wSTgyiO2yWP2fQNh_ltg7jJmgHxeEgHmh586N61-5iaK2EMa7EXMVWEjVhO6AS_GAAHGUm-3lfanvwGVcaW2GfIVflFTHuahulCXqwGdPwEr8N__UjdFBkr4SEEVETBLoycIHCTGeGk3u-bRvy-KX48b67xWwapSE7ZGsnSHZl2aYxTIv__A9TvyMHBepNRlRsV3V-_LqEEzjg1xLS_kHNwcZPfV0OWiJ7DqHCRDTItSHfO02ke2kre1ziBRk4k59YD5bVOxQzdugvJrn2pg")
                .when()
                .get(token.getHost()+"/admin/transactions?"+params));
    }
}
